# Install LEMP on ALT Linux
---
- hosts: alt
  become: true

  vars:
    nginx_port: 80
    php_version: 8.2

  roles:
    - nginx
    - mysql
    - php

  tasks:
    - name: "Restart nginx"
      systemd:
        name: "nginx"
        state: "restarted"
