- name: "Install php{{ php_version }}"
  apt_rpm:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "php{{ php_version }}-fpm-fcgi"
    - "php{{ php_version }}-mysqlnd"
    - "php{{ php_version }}-mysqlnd-mysqli"

- name: "Start and enable php{{ php_version }}-fpm"
  systemd:
    name: "php{{ php_version }}-fpm"
    state: "started"
    enabled: true

- name: "Copy testphp.conf for nginx"
  template:
    src: "templates/testphp.conf.j2"
    dest: /etc/nginx/sites-available.d/testphp.conf

- name: "Activate the configuration"
  file: 
    src: /etc/nginx/sites-available.d/testphp.conf
    dest: /etc/nginx/sites-enabled.d/testphp.conf
    state: "link"

- name: "Create directory /var/www/testphp"
  file:
    path: /var/www/testphp
    recurse: true
    state: "directory"

- name: "Copy our phptest to /var/www/testphp folder"
  copy:
    src: "files/testphp"
    dest: /var/www/
